backend = "glx";
vsync = true;

# Roundy corners
corner-radius = 18;
# round-borders = true

# Exclude bar and launcher from rounding
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  #"class_g = 'Rofi'",
  "window_type = 'dock'"
  # "class_g = 'i3-frame'"
];

# Transparent glass-like effect
inactive-opacity = 0.7;
active-opacity = 1.0;

opacity-rule = [
  #"100:class_g = 'firefox'",
  #"30:class_g = 'Rofi'",
  "100:fullscreen"
];


# Fade animations
fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;

# Blur for glass effect
blur-background = true;
blur-method = "dual_kawase";
blur-size = 100;
blur-strength = 100;
blur-deviation = 5.0;
blur-background-frame = true;

blur-background-exclude = [
  "window_type = 'dock'",
];

shadow = false;
