github.com:
    users:
        luciendberkeley:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: luciendberkeley
