# ============================================================
# Appearance
# ============================================================

# Transparency
background_opacity 0.65

# No Kitty tab bar
tab_bar_style hidden

# ============================================================
# Colors
# ============================================================

# Normal colors
color0  #473738
color1  #c98282
color2  #7fa88a
color3  #c8b878
color4  #7f9bb8
color5  #a88aa8
color6  #7fa8a0
color7  #818f7f

# Bright colors
color8  #5c4a4b
color9  #e09a9a
color10 #9bc49f
color11 #e0d08a
color12 #9bb8d8
color13 #c8a8c8
color14 #9bc8c0
color15 #aab8a8

foreground #aab8a8
cursor #52ad70

font_family JetBrains Mono
font_size 12
text_composition_strategy legacy

cursor_shape block
shell_integration no-cursor

window_padding_width 6 8
